### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by viktoriia-shyian** [viktoriia-shyian/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by ianshy** [comment]
**In less than 10 years, painted almost 900 paintings.**
From November 1881 to July 1890, produced close to 900 paintings. He used peasants and farmers as models and then flowers, landscapes and himself because he was too poor to pay his subjects.

**A prolific correspondent**
Wrote nearly as many letters as created paintings: composed nearly 800 letters, mainly to brother and closest friend Theo.

**Only one painting sold during lifetime**
He sold only one painting while he was alive: The Red Vineyard which went for 400 francs in Belgium seven months before his death. His most expensive painting Portrait of Dr. Gachet was sold for $148.6 million in 1990.

**Only the lobe, not the whole ear was cut off**
Actually, Gauguin lopped off his friend’s lobe while they were fencing and the self-mutilation was concocted between the two to avoid embarrassment and arrest.
